services:
  webshop-db:
    image: mysql:8
    container_name: webshop-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: webshop
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - webshop-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  webshop-backend:
    image: webshop.azurecr.io/webshop-backend:1.0
    container_name: webshop-backend
    environment:
      APP_ENV: production
      DB_USER: root
      DB_PASSWORD: admin
      DB_HOST: webshop-db
      DB_NAME: webshop
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      webshop-db:
        condition: service_healthy

networks:
  app-network:

volumes:
  webshop-db-data:
    driver: local
