"""made address column nullable

Revision ID: 16c9935a6036
Revises: 25ed9cb4769a
Create Date: 2025-02-05 15:39:37.303318

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "16c9935a6036"
down_revision = "25ed9cb4769a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "address", existing_type=mysql.VARCHAR(length=200), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "address", existing_type=mysql.VARCHAR(length=200), nullable=False
        )

    # ### end Alembic commands ###
