"""added is_admin column in user table

Revision ID: 25ed9cb4769a
Revises: baa56209ccc1
Create Date: 2025-02-05 15:14:53.403218

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25ed9cb4769a"
down_revision = "baa56209ccc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_admin", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
