"""added price column in product table

Revision ID: 68b792581c34
Revises: ab8945aa4ecb
Create Date: 2025-02-02 00:08:47.608193

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68b792581c34"
down_revision = "ab8945aa4ecb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("price", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("price")

    # ### end Alembic commands ###
