"""added items_count column in orders table

Revision ID: ab8945aa4ecb
Revises: 1a423f290814
Create Date: 2025-02-02 00:06:39.388129

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab8945aa4ecb"
down_revision = "1a423f290814"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(sa.Column("items_count", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_column("items_count")

    # ### end Alembic commands ###
