"""made product_id foreign key unique under Inventory table

Revision ID: baa56209ccc1
Revises: 4908ccc4f1d4
Create Date: 2025-02-02 14:54:12.022925

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "baa56209ccc1"
down_revision = "4908ccc4f1d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["product_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
