"""made foreign keys not nullable

Revision ID: e4f1d37039ca
Revises: 9e403938f079
Create Date: 2025-02-01 17:02:28.621101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4f1d37039ca'
down_revision = '9e403938f079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
